use std::fmt;

pub enum ISO4217 {
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BOV,
    BRL,
    BSD,
    BTN,
    BWP,
    BYR,
    BZD,
    CAD,
    CDF,
    CHE,
    CHF,
    CHW,
    CLF,
    CLP,
    CNY,
    COP,
    COU,
    CRC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    GBP,
    GEL,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    INR,
    IQD,
    IRR,
    ISK,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LKR,
    LRD,
    LSL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MMK,
    MNT,
    MOP,
    MRO,
    MUR,
    MVR,
    MWK,
    MXN,
    MXV,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SHP,
    SLL,
    SOS,
    SRD,
    SSP,
    STD,
    SVC,
    SYP,
    SZL,
    THB,
    TJS,
    TMT,
    TND,
    TOP,
    TRY,
    TTD,
    TWD,
    TZS,
    UAH,
    UGX,
    USD,
    UYU,
    UZS,
    VEF,
    VND,
    VUV,
    WST,
    XAF,
    XAG,
    XAU,
    XCD,
    XDR,
    XOF,
    XPT,
    XTS,
    XXX,
    YER,
    ZAR,
    ZMK,
}

impl fmt::Display for ISO4217 {
    fn fmt(&self,f: &mut fmt::Formatter) -> fmt::Result {
        use ISO4217::*;
        let r = match *self {
            AED => "UAE Dirham",
            AFN => "Afghani",
            ALL => "Lek",
            AMD => "Armenian Dram",
            ANG => "Netherlands Antillean Guilder",
            AOA => "Kwanza",
            ARS => "Argentine Peso",
            AUD => "Australian Dollar",
            AWG => "Aruban Florin",
            AZN => "Azerbaijanian Manat",
            BAM => "Convertible Mark",
            BBD => "Barbados Dollar",
            BDT => "Taka",
            BGN => "Bulgarian Lev",
            BHD => "Bahraini Dinar",
            BIF => "Burundi Franc",
            BMD => "Bermudian Dollar",
            BND => "Brunei Dollar",
            BOB => "Boliviano",
            BOV => "Mvdol",
            BRL => "Brazilian Real",
            BSD => "Bahamian Dollar",
            BTN => "Ngultrum",
            BWP => "Pula",
            BYR => "Belarussian Ruble",
            BZD => "Belize Dollar",
            CAD => "Canadian Dollar",
            CDF => "Congolese Franc",
            CHE => "WIR Euro",
            CHF => "Swiss franc",
            CHW => "WIR Franc",
            CLF => "Unidad de Fomento",
            CLP => "Chilean Peso",
            CNY => "Yuan Renminbi",
            COP => "Colombian Peso",
            COU => "Unidad de Valor Real",
            CRC => "Costa Rican Colon",
            CUP => "Cuban Peso",
            CVE => "Cabo Verde Escudo",
            CZK => "Czech Koruna",
            DJF => "Djibouti Franc",
            DKK => "Danish Krone",
            DOP => "Dominican Peso",
            DZD => "Algerian Dinar",
            EGP => "Egyptian Pound",
            ERN => "Nakfa",
            ETB => "Ethiopian Birr",
            EUR => "Euro",
            FJD => "Fiji Dollar",
            FKP => "Falkland Islands Pound",
            GBP => "Pound Sterling",
            GEL => "Lari",
            GHS => "Ghana Cedi",
            GIP => "Gibraltar Pound",
            GMD => "Dalasi",
            GNF => "Guinea Franc",
            GTQ => "Quetzal",
            GYD => "Guyana Dollar",
            HKD => "Hong Kong Dollar",
            HNL => "Lempira",
            HRK => "Kuna",
            HTG => "Gourde",
            HUF => "Forint",
            IDR => "Rupiah",
            ILS => "New Israeli Sheqel",
            INR => "Indian Rupee",
            IQD => "Iraqi Dinar",
            IRR => "Iranian Rial",
            ISK => "Iceland Krona",
            JMD => "Jamaican Dollar",
            JOD => "Jordanian Dinar",
            JPY => "Yen",
            KES => "Kenyan Shilling",
            KGS => "Som",
            KHR => "Riel",
            KMF => "Comoro Franc",
            KPW => "North Korean Won",
            KRW => "Won",
            KWD => "Kuwaiti Dinar",
            KYD => "Cayman Islands Dollar",
            KZT => "Tenge",
            LAK => "Kip",
            LBP => "Lebanese Pound",
            LKR => "Sri Lanka Rupee",
            LRD => "Liberian Dollar",
            LSL => "Loti",
            LYD => "Libyan Dinar",
            MAD => "Moroccan Dirham",
            MDL => "Moldovan Leu",
            MGA => "Malagasy Ariary",
            MKD => "Denar",
            MMK => "Kyat",
            MNT => "Tugrik",
            MOP => "Pataca",
            MRO => "Ouguiya",
            MUR => "Mauritius Rupee",
            MVR => "Rufiyaa",
            MWK => "Kwacha",
            MXN => "Mexican Peso",
            MXV => "Mexican Unidad de Inversion (UDI)",
            MYR => "Malaysian Ringgit",
            MZN => "Mozambique Metical",
            NAD => "Namibia Dollar",
            NGN => "Naira",
            NIO => "Cordoba Oro",
            NOK => "Norwegian Krone",
            NPR => "Nepalese Rupee",
            NZD => "New Zealand Dollar",
            OMR => "Rial Omani",
            PAB => "Balboa",
            PEN => "Nuevo Sol",
            PGK => "Kina",
            PHP => "Philippine Peso",
            PKR => "Pakistan Rupee",
            PLN => "Zloty",
            PYG => "Guarani",
            QAR => "Qatari Rial",
            RON => "Romanian Leu",
            RSD => "Serbian Dinar",
            RUB => "Russian Ruble",
            RWF => "Rwanda Franc",
            SAR => "Saudi Riyal",
            SBD => "Solomon Islands Dollar",
            SCR => "Seychelles Rupee",
            SDG => "Sudanese Pound",
            SEK => "Swedish Krona",
            SGD => "Singapore Dollar",
            SHP => "Saint Helena Pound",
            SLL => "Leone",
            SOS => "Somali Shilling",
            SRD => "Surinam Dollar",
            SSP => "South Sudanese Pound",
            STD => "Dobra",
            SVC => "El Salvador Colon",
            SYP => "Syrian Pound",
            SZL => "Lilangeni",
            THB => "Baht",
            TJS => "Somoni",
            TMT => "Turkmenistan New Manat",
            TND => "Tunisian Dinar",
            TOP => "Pa’anga",
            TRY => "Turkish Lira",
            TTD => "Trinidad and Tobago Dollar",
            TWD => "New Taiwan Dollar",
            TZS => "Tanzanian Shilling",
            UAH => "Hryvnia",
            UGX => "Uganda Shilling",
            USD => "US dollar",
            UYU => "Peso Uruguayo",
            UZS => "Uzbekistan Sum",
            VEF => "Bolivar",
            VND => "Dong",
            VUV => "Vatu",
            WST => "Tala",
            XAF => "CFA Franc BEAC",
            XAG => "Silver",
            XAU => "Gold",
            XCD => "East Caribbean Dollar",
            XDR => "SDR (Special Drawing Right)",
            XOF => "CFA Franc BCEAO",
            XPT => "Platinum",
            XTS => "Codes specifically reserved for testing purposes",
            XXX => "The codes assigned for transactions where no currency is involved",
            YER => "Yemeni Rial",
            ZAR => "Rand",
            ZMK => "Zambian kwacha",
        };
        write!(f, "{}", r)
    }
}
